version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - htmlzip

conda:
  environment: environment.yml

python:
  install:
    - method: pip
      path: .
  system_packages: false

build:
  image: latest
