name: Format

on: [push, pull_request]

jobs:

  format:
    name: Check for lint and format code to a standard style
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          python-version: 3.11
          auto-activate-base: false

      - uses: psf/black@stable
        with:
          options: "--check --verbose --diff"
          src: "bmi_topography docs examples tests noxfile.py"

      - name: Lint code
        run: |
          pip install flake8
          flake8 bmi_topography docs examples tests noxfile.py
